### ISSUE TITLE
[paseTimeSelector]

### ISSUE THREAD

**Issue by berber1016** [growingio/gio-design-pro#364]
1. 无法自定义disableDate区间，有需求只能选择过去30天区间，需要有限制可选时间范围。
2. 当使用shortcutFilter过滤，仅保留一个，样式出现问题。
3. 无法取消onCancel icon。

**Comment by jack0pan** [comment]
- 对于 1，把 disabledDate 参数放出来就行；
- 2 和 3 输入 selector 的问题，会在 selector 里修复。
